version: '3'

services:

  db:
    container_name: mydb
    image: mysql:5.5
    hostname: mydb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: vasya
      MYSQL_PASSWORD: 1qaz@WSX
      MYSQL_DATABASE: db_vasya
      MYSQL_ROOT_PASSWORD: 1qaz@WSX

  application:
    container_name: myapp
    hostname: myapp
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: vasya
      DB_PASSWORD: 1qaz@WSX
      DB_IP: mydb
      DB_NAME: db_vasya

volumes:
  db_data:
